app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovieModel(movies)]'. Original exception was: Mapper 'Mapper[OrderModel(orders)]' has no property 'video'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Invalid token
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
app.domain.security.auth_user - ERROR - User auth error: Token has expired
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
app.domain.security.auth_user - ERROR - User auth error: Token has expired
passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/ural/Documents/Webapps/VS_Market/venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
